# This makefile is just a simple "script replacement"
# nothing is realy "made" here. Only OpenOCD will be called.
# (mthomas 11/2006)

program :
	openocd_cm3_beta.exe --file cortex_ft2232_flash.cfg 	

# Listing of phony targets.
.PHONY : program
